### ISSUE TITLE
Set iframe height to PDF height

### ISSUE THREAD

**Issue by simplystuart** [classicalacademicpress/classicalu-acg-files#1]
Using [PDF.js](https://mozilla.github.io/pdf.js/).

[Related Stack Overflow post](https://stackoverflow.com/questions/15004555/how-to-get-height-of-pdf-document-load-in-iframe/18608554#18608554).

**Comment by charlesLoder** [comment]
I assume the pdf's for [ACG](https://classicalu.com/ambrose-curriculum-guide/) are those on the individual pages (e.g. [Kindergarten Center](https://classicalu.com/ambrose-curriculum-guide/acg-kindergarten-center/).

These are `.docx` files, I'm not totally sure if there is a way to determine the page height. Will research more

**Comment by charlesLoder** [comment]
@simplystuart 

We display the ACG files from Google in an `iframe` with the source set to the appropriate file on Google Drive.

These files are `docx`, so we can't simply use PDF.js ([see so question](https://stackoverflow.com/questions/14144069/pdf-js-analog-for-word-documents)).

Additionally (and the greatest reason) because "the link is generated from Google Docs using [Publish to the web](https://support.google.com/a/users/answer/9308870?hl=en)" which "create[s] a copy of your file as a unique webpage with its own URL" that means that the content is webpage and not a `docx` file meaning pagination is (very likely) lost.

Any fixes would require changing the actual files

---

let me know if that makes sense. Happy to walk through it

**Comment by simplystuart** [comment]
@charlesLoder that works! These files might have been PDFs whenever I created this issue, so I am happy with your findings, as that means we can move on.
